[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../../Common
lib_deps =
    madhephaestus/ESP32Encoder @ ^0.11.7
build_flags =
    -Wall
    -Wextra
