[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit BNO055@^1.6.4
    adafruit/Adafruit Unified Sensor@^1.1.15
